//
//  StyleKitName.m
//  ProjectName
//
//  Created by AuthorName on 1/24/15.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "StyleKitName.h"


@implementation StyleKitName

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods


+ (void)drawMainUI2
{
    //// General Declarations
    CGColorSpaceRef colorSpace = CGColorSpaceCreateDeviceRGB();
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* shape74ColorOverlay = [UIColor colorWithRed: 0.365 green: 0.026 blue: 0 alpha: 1];
    UIColor* shape74DropShadowColor = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    UIColor* shape74Copy4ColorOverlay = [UIColor colorWithRed: 0.365 green: 0.026 blue: 0 alpha: 1];
    UIColor* shape74Copy4DropShadowColor = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    UIColor* shape74Copy5ColorOverlay = [UIColor colorWithRed: 0.365 green: 0.026 blue: 0 alpha: 1];
    UIColor* shape74Copy5DropShadowColor = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    UIColor* shape74Copy6ColorOverlay = [UIColor colorWithRed: 0.365 green: 0.026 blue: 0 alpha: 1];
    UIColor* shape74Copy6DropShadowColor = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    UIColor* shape74Copy7ColorOverlay = [UIColor colorWithRed: 0.365 green: 0.026 blue: 0 alpha: 1];
    UIColor* shape74Copy7DropShadowColor = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    UIColor* shape74Copy8ColorOverlay = [UIColor colorWithRed: 0.365 green: 0.026 blue: 0 alpha: 1];
    UIColor* shape74Copy8DropShadowColor = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    UIColor* shape72CopyColor = [UIColor colorWithRed: 0.671 green: 0.045 blue: 0.069 alpha: 1];
    UIColor* color = [UIColor colorWithRed: 0 green: 0 blue: 0 alpha: 1];
    UIColor* color2 = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    UIColor* shape72CopyStrokeColor = [UIColor colorWithRed: 0.463 green: 0.027 blue: 0.047 alpha: 1];
    UIColor* color54CopyColor = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    UIColor* bpmCopyColor = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    UIColor* color101010Color = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    UIColor* kphColor = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    UIColor* rectangle1ColorOverlay = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    UIColor* shape75ColorOverlay = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    UIColor* rectangle1CopyColorOverlay = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    UIColor* color02Color = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    UIColor* kmColor = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    UIColor* shape74CopyColorOverlay = [UIColor colorWithRed: 0.365 green: 0.026 blue: 0 alpha: 1];
    UIColor* shape74CopyDropShadowColor = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    UIColor* shape74Copy2ColorOverlay = [UIColor colorWithRed: 0.365 green: 0.026 blue: 0 alpha: 1];
    UIColor* shape74Copy2DropShadowColor = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    UIColor* shape74Copy3ColorOverlay = [UIColor colorWithRed: 0.365 green: 0.026 blue: 0 alpha: 1];
    UIColor* shape74Copy3DropShadowColor = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];

    //// Gradient Declarations
    CGFloat twoColorLocations[] = {0, 1};
    CGGradientRef twoColor = CGGradientCreateWithColors(colorSpace, (__bridge CFArrayRef)@[(id)color.CGColor, (id)color2.CGColor], twoColorLocations);

    //// Shadow Declarations
    UIColor* shape74DropShadow = [shape74DropShadowColor colorWithAlphaComponent: 0.34];
    CGSize shape74DropShadowOffset = CGSizeMake(-0.6, 0.6);
    CGFloat shape74DropShadowBlurRadius = 1;
    UIColor* shape74Copy4DropShadow = [shape74Copy4DropShadowColor colorWithAlphaComponent: 0.34];
    CGSize shape74Copy4DropShadowOffset = CGSizeMake(-0.6, 0.6);
    CGFloat shape74Copy4DropShadowBlurRadius = 1;
    UIColor* shape74Copy5DropShadow = [shape74Copy5DropShadowColor colorWithAlphaComponent: 0.34];
    CGSize shape74Copy5DropShadowOffset = CGSizeMake(-0.6, 0.6);
    CGFloat shape74Copy5DropShadowBlurRadius = 1;
    UIColor* shape74Copy6DropShadow = [shape74Copy6DropShadowColor colorWithAlphaComponent: 0.34];
    CGSize shape74Copy6DropShadowOffset = CGSizeMake(-0.6, 0.6);
    CGFloat shape74Copy6DropShadowBlurRadius = 1;
    UIColor* shape74Copy7DropShadow = [shape74Copy7DropShadowColor colorWithAlphaComponent: 0.34];
    CGSize shape74Copy7DropShadowOffset = CGSizeMake(-0.6, 0.6);
    CGFloat shape74Copy7DropShadowBlurRadius = 1;
    UIColor* shape74Copy8DropShadow = [shape74Copy8DropShadowColor colorWithAlphaComponent: 0.34];
    CGSize shape74Copy8DropShadowOffset = CGSizeMake(-0.6, 0.6);
    CGFloat shape74Copy8DropShadowBlurRadius = 1;
    UIColor* shape74CopyDropShadow = [shape74CopyDropShadowColor colorWithAlphaComponent: 0.34];
    CGSize shape74CopyDropShadowOffset = CGSizeMake(-0.6, 0.6);
    CGFloat shape74CopyDropShadowBlurRadius = 1;
    UIColor* shape74Copy2DropShadow = [shape74Copy2DropShadowColor colorWithAlphaComponent: 0.34];
    CGSize shape74Copy2DropShadowOffset = CGSizeMake(-0.6, 0.6);
    CGFloat shape74Copy2DropShadowBlurRadius = 1;
    UIColor* shape74Copy3DropShadow = [shape74Copy3DropShadowColor colorWithAlphaComponent: 0.34];
    CGSize shape74Copy3DropShadowOffset = CGSizeMake(-0.6, 0.6);
    CGFloat shape74Copy3DropShadowBlurRadius = 1;

    //// chart
    {
        //// Group 3
        {
            CGContextSaveGState(context);
            CGContextSetAlpha(context, 0.5);
            CGContextBeginTransparencyLayer(context, NULL);


            //// Shape 74 ColorOverlay Drawing
            UIBezierPath* shape74ColorOverlayPath = UIBezierPath.bezierPath;
            [shape74ColorOverlayPath moveToPoint: CGPointMake(939, 1660)];
            [shape74ColorOverlayPath addLineToPoint: CGPointMake(953, 1660)];
            [shape74ColorOverlayPath addLineToPoint: CGPointMake(953, 1750)];
            [shape74ColorOverlayPath addLineToPoint: CGPointMake(939, 1750)];
            [shape74ColorOverlayPath addLineToPoint: CGPointMake(939, 1660)];
            [shape74ColorOverlayPath closePath];
            CGContextSaveGState(context);
            CGContextSetShadowWithColor(context, shape74DropShadowOffset, shape74DropShadowBlurRadius, [shape74DropShadow CGColor]);
            [shape74ColorOverlay setFill];
            [shape74ColorOverlayPath fill];
            CGContextRestoreGState(context);



            CGContextEndTransparencyLayer(context);
            CGContextRestoreGState(context);
        }


        //// Group 5
        {
            CGContextSaveGState(context);
            CGContextSetAlpha(context, 0.5);
            CGContextBeginTransparencyLayer(context, NULL);


            //// Shape 74 copy 4 ColorOverlay Drawing
            UIBezierPath* shape74Copy4ColorOverlayPath = UIBezierPath.bezierPath;
            [shape74Copy4ColorOverlayPath moveToPoint: CGPointMake(975.45, 1649.6)];
            [shape74Copy4ColorOverlayPath addLineToPoint: CGPointMake(981.56, 1637)];
            [shape74Copy4ColorOverlayPath addLineToPoint: CGPointMake(1062.55, 1676.25)];
            [shape74Copy4ColorOverlayPath addLineToPoint: CGPointMake(1056.44, 1688.85)];
            [shape74Copy4ColorOverlayPath addLineToPoint: CGPointMake(975.45, 1649.6)];
            [shape74Copy4ColorOverlayPath closePath];
            CGContextSaveGState(context);
            CGContextSetShadowWithColor(context, shape74Copy4DropShadowOffset, shape74Copy4DropShadowBlurRadius, [shape74Copy4DropShadow CGColor]);
            [shape74Copy4ColorOverlay setFill];
            [shape74Copy4ColorOverlayPath fill];
            CGContextRestoreGState(context);



            CGContextEndTransparencyLayer(context);
            CGContextRestoreGState(context);
        }


        //// Group 7
        {
            CGContextSaveGState(context);
            CGContextSetAlpha(context, 0.5);
            CGContextBeginTransparencyLayer(context, NULL);


            //// Shape 74 copy 5 ColorOverlay Drawing
            UIBezierPath* shape74Copy5ColorOverlayPath = UIBezierPath.bezierPath;
            [shape74Copy5ColorOverlayPath moveToPoint: CGPointMake(988.1, 1588.55)];
            [shape74Copy5ColorOverlayPath addLineToPoint: CGPointMake(987.91, 1574.55)];
            [shape74Copy5ColorOverlayPath addLineToPoint: CGPointMake(1077.9, 1573.3)];
            [shape74Copy5ColorOverlayPath addLineToPoint: CGPointMake(1078.09, 1587.3)];
            [shape74Copy5ColorOverlayPath addLineToPoint: CGPointMake(988.1, 1588.55)];
            [shape74Copy5ColorOverlayPath closePath];
            CGContextSaveGState(context);
            CGContextSetShadowWithColor(context, shape74Copy5DropShadowOffset, shape74Copy5DropShadowBlurRadius, [shape74Copy5DropShadow CGColor]);
            [shape74Copy5ColorOverlay setFill];
            [shape74Copy5ColorOverlayPath fill];
            CGContextRestoreGState(context);



            CGContextEndTransparencyLayer(context);
            CGContextRestoreGState(context);
        }


        //// Group 9
        {
            CGContextSaveGState(context);
            CGContextSetAlpha(context, 0.5);
            CGContextBeginTransparencyLayer(context, NULL);


            //// Shape 74 copy 6 ColorOverlay Drawing
            UIBezierPath* shape74Copy6ColorOverlayPath = UIBezierPath.bezierPath;
            [shape74Copy6ColorOverlayPath moveToPoint: CGPointMake(1002.66, 1536.05)];
            [shape74Copy6ColorOverlayPath addLineToPoint: CGPointMake(995.59, 1531.29)];
            [shape74Copy6ColorOverlayPath addLineToPoint: CGPointMake(1039.66, 1496.55)];
            [shape74Copy6ColorOverlayPath addLineToPoint: CGPointMake(1046.73, 1501.3)];
            [shape74Copy6ColorOverlayPath addLineToPoint: CGPointMake(1002.66, 1536.05)];
            [shape74Copy6ColorOverlayPath closePath];
            CGContextSaveGState(context);
            CGContextSetShadowWithColor(context, shape74Copy6DropShadowOffset, shape74Copy6DropShadowBlurRadius, [shape74Copy6DropShadow CGColor]);
            [shape74Copy6ColorOverlay setFill];
            [shape74Copy6ColorOverlayPath fill];
            CGContextRestoreGState(context);



            CGContextEndTransparencyLayer(context);
            CGContextRestoreGState(context);
        }


        //// Group 11
        {
            CGContextSaveGState(context);
            CGContextSetAlpha(context, 0.5);
            CGContextBeginTransparencyLayer(context, NULL);


            //// Shape 74 copy 7 ColorOverlay Drawing
            UIBezierPath* shape74Copy7ColorOverlayPath = UIBezierPath.bezierPath;
            [shape74Copy7ColorOverlayPath moveToPoint: CGPointMake(880.95, 1540.99)];
            [shape74Copy7ColorOverlayPath addLineToPoint: CGPointMake(888, 1536.17)];
            [shape74Copy7ColorOverlayPath addLineToPoint: CGPointMake(844.04, 1500.99)];
            [shape74Copy7ColorOverlayPath addLineToPoint: CGPointMake(836.98, 1505.8)];
            [shape74Copy7ColorOverlayPath addLineToPoint: CGPointMake(880.95, 1540.99)];
            [shape74Copy7ColorOverlayPath closePath];
            CGContextSaveGState(context);
            CGContextSetShadowWithColor(context, shape74Copy7DropShadowOffset, shape74Copy7DropShadowBlurRadius, [shape74Copy7DropShadow CGColor]);
            [shape74Copy7ColorOverlay setFill];
            [shape74Copy7ColorOverlayPath fill];
            CGContextRestoreGState(context);



            CGContextEndTransparencyLayer(context);
            CGContextRestoreGState(context);
        }


        //// Group 13
        {
            CGContextSaveGState(context);
            CGContextSetAlpha(context, 0.5);
            CGContextBeginTransparencyLayer(context, NULL);


            //// Shape 74 copy 8 ColorOverlay Drawing
            UIBezierPath* shape74Copy8ColorOverlayPath = UIBezierPath.bezierPath;
            [shape74Copy8ColorOverlayPath moveToPoint: CGPointMake(941.3, 1523.7)];
            [shape74Copy8ColorOverlayPath addLineToPoint: CGPointMake(949.36, 1526.54)];
            [shape74Copy8ColorOverlayPath addLineToPoint: CGPointMake(951.71, 1470.28)];
            [shape74Copy8ColorOverlayPath addLineToPoint: CGPointMake(943.66, 1467.44)];
            [shape74Copy8ColorOverlayPath addLineToPoint: CGPointMake(941.3, 1523.7)];
            [shape74Copy8ColorOverlayPath closePath];
            CGContextSaveGState(context);
            CGContextSetShadowWithColor(context, shape74Copy8DropShadowOffset, shape74Copy8DropShadowBlurRadius, [shape74Copy8DropShadow CGColor]);
            [shape74Copy8ColorOverlay setFill];
            [shape74Copy8ColorOverlayPath fill];
            CGContextRestoreGState(context);



            CGContextEndTransparencyLayer(context);
            CGContextRestoreGState(context);
        }


        //// bpm
        {
            //// Group 18
            {
                //// Shape 72 copy Drawing
                UIBezierPath* shape72CopyPath = UIBezierPath.bezierPath;
                [shape72CopyPath moveToPoint: CGPointMake(947, 1723)];
                [shape72CopyPath addCurveToPoint: CGPointMake(995, 1771) controlPoint1: CGPointMake(973.51, 1723) controlPoint2: CGPointMake(995, 1744.49)];
                [shape72CopyPath addCurveToPoint: CGPointMake(947, 1819) controlPoint1: CGPointMake(995, 1797.51) controlPoint2: CGPointMake(973.51, 1819)];
                [shape72CopyPath addCurveToPoint: CGPointMake(899, 1771) controlPoint1: CGPointMake(920.49, 1819) controlPoint2: CGPointMake(899, 1797.51)];
                [shape72CopyPath addCurveToPoint: CGPointMake(947, 1723) controlPoint1: CGPointMake(899, 1744.49) controlPoint2: CGPointMake(920.49, 1723)];
                [shape72CopyPath closePath];
                [shape72CopyColor setFill];
                [shape72CopyPath fill];


                //// Group 15
                {
                    CGContextSaveGState(context);
                    CGContextTranslateCTM(context, 135, 3138);

                    CGContextSetBlendMode(context, kCGBlendModeMultiply);
                    CGContextBeginTransparencyLayer(context, NULL);


                    CGContextEndTransparencyLayer(context);

                    CGContextRestoreGState(context);
                }


                //// Group 17
                {
                    CGContextSaveGState(context);
                    CGContextTranslateCTM(context, 135, 3138);

                    CGContextSetAlpha(context, 0.15);
                    CGContextSetBlendMode(context, kCGBlendModeSoftLight);
                    CGContextBeginTransparencyLayer(context, NULL);


                    //// Shape 72 copy GradientOverlay Drawing
                    UIBezierPath* shape72CopyGradientOverlayPath = UIBezierPath.bezierPath;
                    [shape72CopyGradientOverlayPath moveToPoint: CGPointMake(812, -1415)];
                    [shape72CopyGradientOverlayPath addCurveToPoint: CGPointMake(860, -1367) controlPoint1: CGPointMake(838.51, -1415) controlPoint2: CGPointMake(860, -1393.51)];
                    [shape72CopyGradientOverlayPath addCurveToPoint: CGPointMake(812, -1319) controlPoint1: CGPointMake(860, -1340.49) controlPoint2: CGPointMake(838.51, -1319)];
                    [shape72CopyGradientOverlayPath addCurveToPoint: CGPointMake(764, -1367) controlPoint1: CGPointMake(785.49, -1319) controlPoint2: CGPointMake(764, -1340.49)];
                    [shape72CopyGradientOverlayPath addCurveToPoint: CGPointMake(812, -1415) controlPoint1: CGPointMake(764, -1393.51) controlPoint2: CGPointMake(785.49, -1415)];
                    [shape72CopyGradientOverlayPath closePath];
                    CGContextSaveGState(context);
                    [shape72CopyGradientOverlayPath addClip];
                    CGContextDrawLinearGradient(context, twoColor,
                        CGPointMake(812, -1319),
                        CGPointMake(812, -1415),
                        kCGGradientDrawsBeforeStartLocation | kCGGradientDrawsAfterEndLocation);
                    CGContextRestoreGState(context);
                    [shape72CopyStrokeColor setStroke];
                    shape72CopyGradientOverlayPath.lineWidth = 8;
                    [shape72CopyGradientOverlayPath stroke];


                    CGContextEndTransparencyLayer(context);

                    CGContextRestoreGState(context);
                }
            }


            //// Graphic 54 copy Drawing
            CGRect graphic54CopyRect = CGRectMake(913.39, 1742, 66.61, 35);
            NSMutableParagraphStyle* graphic54CopyStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
            graphic54CopyStyle.alignment = NSTextAlignmentCenter;

            NSDictionary* graphic54CopyFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"Helvetica" size: 27], NSForegroundColorAttributeName: color54CopyColor, NSParagraphStyleAttributeName: graphic54CopyStyle};

            [@"9999" drawInRect: graphic54CopyRect withAttributes: graphic54CopyFontAttributes];


            //// bpm copy Drawing
            CGRect bpmCopyRect = CGRectMake(917, 1777, 60, 23);
            NSMutableParagraphStyle* bpmCopyStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
            bpmCopyStyle.alignment = NSTextAlignmentCenter;

            NSDictionary* bpmCopyFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"Helvetica" size: 18], NSForegroundColorAttributeName: bpmCopyColor, NSParagraphStyleAttributeName: bpmCopyStyle};

            [@"steps" drawInRect: bpmCopyRect withAttributes: bpmCopyFontAttributes];
        }


        //// km
        {
            //// Group 23
            {
                //// Shape 72 copy 2 Drawing
                UIBezierPath* shape72Copy2Path = UIBezierPath.bezierPath;
                [shape72Copy2Path moveToPoint: CGPointMake(1079.5, 1652)];
                [shape72Copy2Path addCurveToPoint: CGPointMake(1120, 1692.5) controlPoint1: CGPointMake(1101.87, 1652) controlPoint2: CGPointMake(1120, 1670.13)];
                [shape72Copy2Path addCurveToPoint: CGPointMake(1079.5, 1733) controlPoint1: CGPointMake(1120, 1714.87) controlPoint2: CGPointMake(1101.87, 1733)];
                [shape72Copy2Path addCurveToPoint: CGPointMake(1039, 1692.5) controlPoint1: CGPointMake(1057.13, 1733) controlPoint2: CGPointMake(1039, 1714.87)];
                [shape72Copy2Path addCurveToPoint: CGPointMake(1079.5, 1652) controlPoint1: CGPointMake(1039, 1670.13) controlPoint2: CGPointMake(1057.13, 1652)];
                [shape72Copy2Path closePath];
                [shape72CopyColor setFill];
                [shape72Copy2Path fill];


                //// Group 20
                {
                    CGContextSaveGState(context);
                    CGContextTranslateCTM(context, 139, 3120);

                    CGContextSetBlendMode(context, kCGBlendModeMultiply);
                    CGContextBeginTransparencyLayer(context, NULL);


                    CGContextEndTransparencyLayer(context);

                    CGContextRestoreGState(context);
                }


                //// Group 22
                {
                    CGContextSaveGState(context);
                    CGContextTranslateCTM(context, 139, 3120);

                    CGContextSetAlpha(context, 0.15);
                    CGContextSetBlendMode(context, kCGBlendModeSoftLight);
                    CGContextBeginTransparencyLayer(context, NULL);


                    //// Shape 72 copy GradientOverlay Drawing
                    UIBezierPath* shape72CopyGradientOverlayPath = UIBezierPath.bezierPath;
                    [shape72CopyGradientOverlayPath moveToPoint: CGPointMake(940.5, -1468)];
                    [shape72CopyGradientOverlayPath addCurveToPoint: CGPointMake(981, -1427.5) controlPoint1: CGPointMake(962.87, -1468) controlPoint2: CGPointMake(981, -1449.87)];
                    [shape72CopyGradientOverlayPath addCurveToPoint: CGPointMake(940.5, -1387) controlPoint1: CGPointMake(981, -1405.13) controlPoint2: CGPointMake(962.87, -1387)];
                    [shape72CopyGradientOverlayPath addCurveToPoint: CGPointMake(900, -1427.5) controlPoint1: CGPointMake(918.13, -1387) controlPoint2: CGPointMake(900, -1405.13)];
                    [shape72CopyGradientOverlayPath addCurveToPoint: CGPointMake(940.5, -1468) controlPoint1: CGPointMake(900, -1449.87) controlPoint2: CGPointMake(918.13, -1468)];
                    [shape72CopyGradientOverlayPath closePath];
                    CGContextSaveGState(context);
                    [shape72CopyGradientOverlayPath addClip];
                    CGContextDrawLinearGradient(context, twoColor,
                        CGPointMake(940.5, -1387),
                        CGPointMake(940.5, -1468),
                        kCGGradientDrawsBeforeStartLocation | kCGGradientDrawsAfterEndLocation);
                    CGContextRestoreGState(context);
                    [shape72CopyStrokeColor setStroke];
                    shape72CopyGradientOverlayPath.lineWidth = 8;
                    [shape72CopyGradientOverlayPath stroke];


                    CGContextEndTransparencyLayer(context);

                    CGContextRestoreGState(context);
                }
            }


            //// Graphic 10:10:10 Drawing
            CGRect graphic101010Rect = CGRectMake(1042.78, 1683, 70.22, 25);
            NSMutableParagraphStyle* graphic101010Style = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
            graphic101010Style.alignment = NSTextAlignmentCenter;

            NSDictionary* graphic101010FontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"MyriadPro-Regular" size: 18.33], NSForegroundColorAttributeName: color101010Color, NSParagraphStyleAttributeName: graphic101010Style};

            [@"10:10:10" drawInRect: graphic101010Rect withAttributes: graphic101010FontAttributes];
        }


        //// KPH
        {
            //// Group 28
            {
                //// Shape 72 copy 3 Drawing
                UIBezierPath* shape72Copy3Path = UIBezierPath.bezierPath;
                [shape72Copy3Path moveToPoint: CGPointMake(1094.5, 1548)];
                [shape72Copy3Path addCurveToPoint: CGPointMake(1125, 1578.5) controlPoint1: CGPointMake(1111.34, 1548) controlPoint2: CGPointMake(1125, 1561.66)];
                [shape72Copy3Path addCurveToPoint: CGPointMake(1094.5, 1609) controlPoint1: CGPointMake(1125, 1595.34) controlPoint2: CGPointMake(1111.34, 1609)];
                [shape72Copy3Path addCurveToPoint: CGPointMake(1064, 1578.5) controlPoint1: CGPointMake(1077.66, 1609) controlPoint2: CGPointMake(1064, 1595.34)];
                [shape72Copy3Path addCurveToPoint: CGPointMake(1094.5, 1548) controlPoint1: CGPointMake(1064, 1561.66) controlPoint2: CGPointMake(1077.66, 1548)];
                [shape72Copy3Path closePath];
                [shape72CopyColor setFill];
                [shape72Copy3Path fill];


                //// Group 25
                {
                    CGContextSaveGState(context);
                    CGContextTranslateCTM(context, 138, 3125);

                    CGContextSetBlendMode(context, kCGBlendModeMultiply);
                    CGContextBeginTransparencyLayer(context, NULL);


                    CGContextEndTransparencyLayer(context);

                    CGContextRestoreGState(context);
                }


                //// Group 27
                {
                    CGContextSaveGState(context);
                    CGContextTranslateCTM(context, 138, 3125);

                    CGContextSetAlpha(context, 0.15);
                    CGContextSetBlendMode(context, kCGBlendModeSoftLight);
                    CGContextBeginTransparencyLayer(context, NULL);


                    //// Shape 72 copy GradientOverlay Drawing
                    UIBezierPath* shape72CopyGradientOverlayPath = UIBezierPath.bezierPath;
                    [shape72CopyGradientOverlayPath moveToPoint: CGPointMake(956.5, -1577)];
                    [shape72CopyGradientOverlayPath addCurveToPoint: CGPointMake(987, -1546.5) controlPoint1: CGPointMake(973.34, -1577) controlPoint2: CGPointMake(987, -1563.34)];
                    [shape72CopyGradientOverlayPath addCurveToPoint: CGPointMake(956.5, -1516) controlPoint1: CGPointMake(987, -1529.66) controlPoint2: CGPointMake(973.34, -1516)];
                    [shape72CopyGradientOverlayPath addCurveToPoint: CGPointMake(926, -1546.5) controlPoint1: CGPointMake(939.66, -1516) controlPoint2: CGPointMake(926, -1529.66)];
                    [shape72CopyGradientOverlayPath addCurveToPoint: CGPointMake(956.5, -1577) controlPoint1: CGPointMake(926, -1563.34) controlPoint2: CGPointMake(939.66, -1577)];
                    [shape72CopyGradientOverlayPath closePath];
                    CGContextSaveGState(context);
                    [shape72CopyGradientOverlayPath addClip];
                    CGContextDrawLinearGradient(context, twoColor,
                        CGPointMake(956.5, -1516),
                        CGPointMake(956.5, -1577),
                        kCGGradientDrawsBeforeStartLocation | kCGGradientDrawsAfterEndLocation);
                    CGContextRestoreGState(context);
                    [shape72CopyStrokeColor setStroke];
                    shape72CopyGradientOverlayPath.lineWidth = 8;
                    [shape72CopyGradientOverlayPath stroke];


                    CGContextEndTransparencyLayer(context);

                    CGContextRestoreGState(context);
                }
            }


            //// kph Drawing
            CGRect kphRect = CGRectMake(1071.93, 1564, 48.07, 34);
            NSMutableParagraphStyle* kphStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
            kphStyle.alignment = NSTextAlignmentCenter;

            NSDictionary* kphFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"Helvetica" size: 22.33], NSForegroundColorAttributeName: kphColor, NSParagraphStyleAttributeName: kphStyle};

            [@"kph" drawInRect: kphRect withAttributes: kphFontAttributes];
        }


        //// stop
        {
            //// Group 33
            {
                //// Shape 72 copy 4 Drawing
                UIBezierPath* shape72Copy4Path = UIBezierPath.bezierPath;
                [shape72Copy4Path moveToPoint: CGPointMake(1048.75, 1463)];
                [shape72Copy4Path addCurveToPoint: CGPointMake(1073.5, 1487.75) controlPoint1: CGPointMake(1062.42, 1463) controlPoint2: CGPointMake(1073.5, 1474.08)];
                [shape72Copy4Path addCurveToPoint: CGPointMake(1048.75, 1512.5) controlPoint1: CGPointMake(1073.5, 1501.42) controlPoint2: CGPointMake(1062.42, 1512.5)];
                [shape72Copy4Path addCurveToPoint: CGPointMake(1024, 1487.75) controlPoint1: CGPointMake(1035.08, 1512.5) controlPoint2: CGPointMake(1024, 1501.42)];
                [shape72Copy4Path addCurveToPoint: CGPointMake(1048.75, 1463) controlPoint1: CGPointMake(1024, 1474.08) controlPoint2: CGPointMake(1035.08, 1463)];
                [shape72Copy4Path closePath];
                [shape72CopyColor setFill];
                [shape72Copy4Path fill];


                //// Group 30
                {
                    CGContextSaveGState(context);
                    CGContextTranslateCTM(context, 143, 3124);

                    CGContextSetBlendMode(context, kCGBlendModeMultiply);
                    CGContextBeginTransparencyLayer(context, NULL);


                    CGContextEndTransparencyLayer(context);

                    CGContextRestoreGState(context);
                }


                //// Group 32
                {
                    CGContextSaveGState(context);
                    CGContextTranslateCTM(context, 143, 3124);

                    CGContextSetAlpha(context, 0.15);
                    CGContextSetBlendMode(context, kCGBlendModeSoftLight);
                    CGContextBeginTransparencyLayer(context, NULL);


                    //// Shape 72 copy GradientOverlay Drawing
                    UIBezierPath* shape72CopyGradientOverlayPath = UIBezierPath.bezierPath;
                    [shape72CopyGradientOverlayPath moveToPoint: CGPointMake(905.75, -1661)];
                    [shape72CopyGradientOverlayPath addCurveToPoint: CGPointMake(930.5, -1636.25) controlPoint1: CGPointMake(919.42, -1661) controlPoint2: CGPointMake(930.5, -1649.92)];
                    [shape72CopyGradientOverlayPath addCurveToPoint: CGPointMake(905.75, -1611.5) controlPoint1: CGPointMake(930.5, -1622.58) controlPoint2: CGPointMake(919.42, -1611.5)];
                    [shape72CopyGradientOverlayPath addCurveToPoint: CGPointMake(881, -1636.25) controlPoint1: CGPointMake(892.08, -1611.5) controlPoint2: CGPointMake(881, -1622.58)];
                    [shape72CopyGradientOverlayPath addCurveToPoint: CGPointMake(905.75, -1661) controlPoint1: CGPointMake(881, -1649.92) controlPoint2: CGPointMake(892.08, -1661)];
                    [shape72CopyGradientOverlayPath closePath];
                    CGContextSaveGState(context);
                    [shape72CopyGradientOverlayPath addClip];
                    CGContextDrawLinearGradient(context, twoColor,
                        CGPointMake(905.75, -1611.5),
                        CGPointMake(905.75, -1661),
                        kCGGradientDrawsBeforeStartLocation | kCGGradientDrawsAfterEndLocation);
                    CGContextRestoreGState(context);
                    [shape72CopyStrokeColor setStroke];
                    shape72CopyGradientOverlayPath.lineWidth = 8;
                    [shape72CopyGradientOverlayPath stroke];


                    CGContextEndTransparencyLayer(context);

                    CGContextRestoreGState(context);
                }
            }


            //// Rectangle 1 ColorOverlay 2 Drawing
            UIBezierPath* rectangle1ColorOverlay2Path = UIBezierPath.bezierPath;
            [rectangle1ColorOverlay2Path moveToPoint: CGPointMake(1041, 1480)];
            [rectangle1ColorOverlay2Path addLineToPoint: CGPointMake(1057, 1480)];
            [rectangle1ColorOverlay2Path addLineToPoint: CGPointMake(1057, 1496)];
            [rectangle1ColorOverlay2Path addLineToPoint: CGPointMake(1041, 1496)];
            [rectangle1ColorOverlay2Path addLineToPoint: CGPointMake(1041, 1480)];
            [rectangle1ColorOverlay2Path closePath];
            [rectangle1ColorOverlay setFill];
            [rectangle1ColorOverlay2Path fill];
        }


        //// stop copy
        {
            //// Group 42
            {
                //// Shape 72 copy 5 Drawing
                UIBezierPath* shape72Copy5Path = UIBezierPath.bezierPath;
                [shape72Copy5Path moveToPoint: CGPointMake(835.75, 1473)];
                [shape72Copy5Path addCurveToPoint: CGPointMake(860.5, 1497.75) controlPoint1: CGPointMake(849.42, 1473) controlPoint2: CGPointMake(860.5, 1484.08)];
                [shape72Copy5Path addCurveToPoint: CGPointMake(835.75, 1522.5) controlPoint1: CGPointMake(860.5, 1511.42) controlPoint2: CGPointMake(849.42, 1522.5)];
                [shape72Copy5Path addCurveToPoint: CGPointMake(811, 1497.75) controlPoint1: CGPointMake(822.08, 1522.5) controlPoint2: CGPointMake(811, 1511.42)];
                [shape72Copy5Path addCurveToPoint: CGPointMake(835.75, 1473) controlPoint1: CGPointMake(811, 1484.08) controlPoint2: CGPointMake(822.08, 1473)];
                [shape72Copy5Path closePath];
                [shape72CopyColor setFill];
                [shape72Copy5Path fill];


                //// Group 39
                {
                    CGContextSaveGState(context);
                    CGContextTranslateCTM(context, 137, 3132);

                    CGContextSetBlendMode(context, kCGBlendModeMultiply);
                    CGContextBeginTransparencyLayer(context, NULL);


                    CGContextEndTransparencyLayer(context);

                    CGContextRestoreGState(context);
                }


                //// Group 41
                {
                    CGContextSaveGState(context);
                    CGContextTranslateCTM(context, 137, 3132);

                    CGContextSetAlpha(context, 0.15);
                    CGContextSetBlendMode(context, kCGBlendModeSoftLight);
                    CGContextBeginTransparencyLayer(context, NULL);


                    //// Shape 72 copy GradientOverlay Drawing
                    UIBezierPath* shape72CopyGradientOverlayPath = UIBezierPath.bezierPath;
                    [shape72CopyGradientOverlayPath moveToPoint: CGPointMake(698.75, -1659)];
                    [shape72CopyGradientOverlayPath addCurveToPoint: CGPointMake(723.5, -1634.25) controlPoint1: CGPointMake(712.42, -1659) controlPoint2: CGPointMake(723.5, -1647.92)];
                    [shape72CopyGradientOverlayPath addCurveToPoint: CGPointMake(698.75, -1609.5) controlPoint1: CGPointMake(723.5, -1620.58) controlPoint2: CGPointMake(712.42, -1609.5)];
                    [shape72CopyGradientOverlayPath addCurveToPoint: CGPointMake(674, -1634.25) controlPoint1: CGPointMake(685.08, -1609.5) controlPoint2: CGPointMake(674, -1620.58)];
                    [shape72CopyGradientOverlayPath addCurveToPoint: CGPointMake(698.75, -1659) controlPoint1: CGPointMake(674, -1647.92) controlPoint2: CGPointMake(685.08, -1659)];
                    [shape72CopyGradientOverlayPath closePath];
                    CGContextSaveGState(context);
                    [shape72CopyGradientOverlayPath addClip];
                    CGContextDrawLinearGradient(context, twoColor,
                        CGPointMake(698.75, -1609.5),
                        CGPointMake(698.75, -1659),
                        kCGGradientDrawsBeforeStartLocation | kCGGradientDrawsAfterEndLocation);
                    CGContextRestoreGState(context);
                    [shape72CopyStrokeColor setStroke];
                    shape72CopyGradientOverlayPath.lineWidth = 8;
                    [shape72CopyGradientOverlayPath stroke];


                    CGContextEndTransparencyLayer(context);

                    CGContextRestoreGState(context);
                }
            }


            //// Shape 75 ColorOverlay 2 Drawing
            UIBezierPath* shape75ColorOverlay2Path = UIBezierPath.bezierPath;
            [shape75ColorOverlay2Path moveToPoint: CGPointMake(848, 1498.5)];
            [shape75ColorOverlay2Path addLineToPoint: CGPointMake(828, 1487)];
            [shape75ColorOverlay2Path addLineToPoint: CGPointMake(828, 1510)];
            [shape75ColorOverlay2Path addLineToPoint: CGPointMake(848, 1498.5)];
            [shape75ColorOverlay2Path closePath];
            [shape75ColorOverlay setFill];
            [shape75ColorOverlay2Path fill];
        }


        //// stop copy 2
        {
            //// Group 51
            {
                //// Shape 72 copy 6 Drawing
                UIBezierPath* shape72Copy6Path = UIBezierPath.bezierPath;
                [shape72Copy6Path moveToPoint: CGPointMake(947.75, 1431)];
                [shape72Copy6Path addCurveToPoint: CGPointMake(972.5, 1455.75) controlPoint1: CGPointMake(961.42, 1431) controlPoint2: CGPointMake(972.5, 1442.08)];
                [shape72Copy6Path addCurveToPoint: CGPointMake(947.75, 1480.5) controlPoint1: CGPointMake(972.5, 1469.42) controlPoint2: CGPointMake(961.42, 1480.5)];
                [shape72Copy6Path addCurveToPoint: CGPointMake(923, 1455.75) controlPoint1: CGPointMake(934.08, 1480.5) controlPoint2: CGPointMake(923, 1469.42)];
                [shape72Copy6Path addCurveToPoint: CGPointMake(947.75, 1431) controlPoint1: CGPointMake(923, 1442.08) controlPoint2: CGPointMake(934.08, 1431)];
                [shape72Copy6Path closePath];
                [shape72CopyColor setFill];
                [shape72Copy6Path fill];


                //// Group 48
                {
                    CGContextSaveGState(context);
                    CGContextTranslateCTM(context, 138, 3125);

                    CGContextSetBlendMode(context, kCGBlendModeMultiply);
                    CGContextBeginTransparencyLayer(context, NULL);


                    CGContextEndTransparencyLayer(context);

                    CGContextRestoreGState(context);
                }


                //// Group 50
                {
                    CGContextSaveGState(context);
                    CGContextTranslateCTM(context, 138, 3125);

                    CGContextSetAlpha(context, 0.15);
                    CGContextSetBlendMode(context, kCGBlendModeSoftLight);
                    CGContextBeginTransparencyLayer(context, NULL);


                    //// Shape 72 copy GradientOverlay Drawing
                    UIBezierPath* shape72CopyGradientOverlayPath = UIBezierPath.bezierPath;
                    [shape72CopyGradientOverlayPath moveToPoint: CGPointMake(809.75, -1694)];
                    [shape72CopyGradientOverlayPath addCurveToPoint: CGPointMake(834.5, -1669.25) controlPoint1: CGPointMake(823.42, -1694) controlPoint2: CGPointMake(834.5, -1682.92)];
                    [shape72CopyGradientOverlayPath addCurveToPoint: CGPointMake(809.75, -1644.5) controlPoint1: CGPointMake(834.5, -1655.58) controlPoint2: CGPointMake(823.42, -1644.5)];
                    [shape72CopyGradientOverlayPath addCurveToPoint: CGPointMake(785, -1669.25) controlPoint1: CGPointMake(796.08, -1644.5) controlPoint2: CGPointMake(785, -1655.58)];
                    [shape72CopyGradientOverlayPath addCurveToPoint: CGPointMake(809.75, -1694) controlPoint1: CGPointMake(785, -1682.92) controlPoint2: CGPointMake(796.08, -1694)];
                    [shape72CopyGradientOverlayPath closePath];
                    CGContextSaveGState(context);
                    [shape72CopyGradientOverlayPath addClip];
                    CGContextDrawLinearGradient(context, twoColor,
                        CGPointMake(809.75, -1644.5),
                        CGPointMake(809.75, -1694),
                        kCGGradientDrawsBeforeStartLocation | kCGGradientDrawsAfterEndLocation);
                    CGContextRestoreGState(context);
                    [shape72CopyStrokeColor setStroke];
                    shape72CopyGradientOverlayPath.lineWidth = 8;
                    [shape72CopyGradientOverlayPath stroke];


                    CGContextEndTransparencyLayer(context);

                    CGContextRestoreGState(context);
                }
            }


            //// Rectangle 1 ColorOverlay 3 Drawing
            UIBezierPath* rectangle1ColorOverlay3Path = UIBezierPath.bezierPath;
            [rectangle1ColorOverlay3Path moveToPoint: CGPointMake(938, 1445)];
            [rectangle1ColorOverlay3Path addLineToPoint: CGPointMake(945, 1445)];
            [rectangle1ColorOverlay3Path addLineToPoint: CGPointMake(945, 1467)];
            [rectangle1ColorOverlay3Path addLineToPoint: CGPointMake(938, 1467)];
            [rectangle1ColorOverlay3Path addLineToPoint: CGPointMake(938, 1445)];
            [rectangle1ColorOverlay3Path closePath];
            [rectangle1ColorOverlay setFill];
            [rectangle1ColorOverlay3Path fill];


            //// Rectangle 1 copy ColorOverlay 2 Drawing
            UIBezierPath* rectangle1CopyColorOverlay2Path = UIBezierPath.bezierPath;
            [rectangle1CopyColorOverlay2Path moveToPoint: CGPointMake(949, 1445)];
            [rectangle1CopyColorOverlay2Path addLineToPoint: CGPointMake(956, 1445)];
            [rectangle1CopyColorOverlay2Path addLineToPoint: CGPointMake(956, 1467)];
            [rectangle1CopyColorOverlay2Path addLineToPoint: CGPointMake(949, 1467)];
            [rectangle1CopyColorOverlay2Path addLineToPoint: CGPointMake(949, 1445)];
            [rectangle1CopyColorOverlay2Path closePath];
            [rectangle1CopyColorOverlay setFill];
            [rectangle1CopyColorOverlay2Path fill];
        }


        //// km main
        {
            //// Group 68
            {
                //// Shape 72 copy 7 Drawing
                UIBezierPath* shape72Copy7Path = UIBezierPath.bezierPath;
                [shape72Copy7Path moveToPoint: CGPointMake(943.5, 1512)];
                [shape72Copy7Path addCurveToPoint: CGPointMake(1027, 1595.5) controlPoint1: CGPointMake(989.62, 1512) controlPoint2: CGPointMake(1027, 1549.38)];
                [shape72Copy7Path addCurveToPoint: CGPointMake(943.5, 1679) controlPoint1: CGPointMake(1027, 1641.62) controlPoint2: CGPointMake(989.62, 1679)];
                [shape72Copy7Path addCurveToPoint: CGPointMake(860, 1595.5) controlPoint1: CGPointMake(897.38, 1679) controlPoint2: CGPointMake(860, 1641.62)];
                [shape72Copy7Path addCurveToPoint: CGPointMake(943.5, 1512) controlPoint1: CGPointMake(860, 1549.38) controlPoint2: CGPointMake(897.38, 1512)];
                [shape72Copy7Path closePath];
                [shape72CopyColor setFill];
                [shape72Copy7Path fill];


                //// Group 65
                {
                    CGContextSaveGState(context);
                    CGContextTranslateCTM(context, 137, 3124);

                    CGContextSetBlendMode(context, kCGBlendModeMultiply);
                    CGContextBeginTransparencyLayer(context, NULL);


                    CGContextEndTransparencyLayer(context);

                    CGContextRestoreGState(context);
                }


                //// Group 67
                {
                    CGContextSaveGState(context);
                    CGContextTranslateCTM(context, 137, 3124);

                    CGContextSetAlpha(context, 0.15);
                    CGContextSetBlendMode(context, kCGBlendModeSoftLight);
                    CGContextBeginTransparencyLayer(context, NULL);


                    //// Shape 72 copy GradientOverlay Drawing
                    UIBezierPath* shape72CopyGradientOverlayPath = UIBezierPath.bezierPath;
                    [shape72CopyGradientOverlayPath moveToPoint: CGPointMake(806.5, -1612)];
                    [shape72CopyGradientOverlayPath addCurveToPoint: CGPointMake(890, -1528.5) controlPoint1: CGPointMake(852.62, -1612) controlPoint2: CGPointMake(890, -1574.62)];
                    [shape72CopyGradientOverlayPath addCurveToPoint: CGPointMake(806.5, -1445) controlPoint1: CGPointMake(890, -1482.38) controlPoint2: CGPointMake(852.62, -1445)];
                    [shape72CopyGradientOverlayPath addCurveToPoint: CGPointMake(723, -1528.5) controlPoint1: CGPointMake(760.38, -1445) controlPoint2: CGPointMake(723, -1482.38)];
                    [shape72CopyGradientOverlayPath addCurveToPoint: CGPointMake(806.5, -1612) controlPoint1: CGPointMake(723, -1574.62) controlPoint2: CGPointMake(760.38, -1612)];
                    [shape72CopyGradientOverlayPath closePath];
                    CGContextSaveGState(context);
                    [shape72CopyGradientOverlayPath addClip];
                    CGContextDrawLinearGradient(context, twoColor,
                        CGPointMake(806.5, -1445),
                        CGPointMake(806.5, -1612),
                        kCGGradientDrawsBeforeStartLocation | kCGGradientDrawsAfterEndLocation);
                    CGContextRestoreGState(context);
                    [shape72CopyStrokeColor setStroke];
                    shape72CopyGradientOverlayPath.lineWidth = 8;
                    [shape72CopyGradientOverlayPath stroke];


                    CGContextEndTransparencyLayer(context);

                    CGContextRestoreGState(context);
                }
            }


            //// Graphic 0.2 Drawing
            CGRect graphic02Rect = CGRectMake(888, 1543, 116, 77);
            NSMutableParagraphStyle* graphic02Style = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
            graphic02Style.alignment = NSTextAlignmentCenter;

            NSDictionary* graphic02FontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"Helvetica-Bold" size: 63.67], NSForegroundColorAttributeName: color02Color, NSParagraphStyleAttributeName: graphic02Style};

            [@"0.2" drawInRect: graphic02Rect withAttributes: graphic02FontAttributes];


            //// km 2 Drawing
            CGRect km2Rect = CGRectMake(875, 1620, 141, 29);
            NSMutableParagraphStyle* km2Style = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
            km2Style.alignment = NSTextAlignmentCenter;

            NSDictionary* km2FontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"Helvetica-Bold" size: 25], NSForegroundColorAttributeName: kmColor, NSParagraphStyleAttributeName: km2Style};

            [@"km" drawInRect: km2Rect withAttributes: km2FontAttributes];
        }


        //// Group 70
        {
            CGContextSaveGState(context);
            CGContextSetAlpha(context, 0.5);
            CGContextBeginTransparencyLayer(context, NULL);


            //// Shape 74 copy ColorOverlay Drawing
            UIBezierPath* shape74CopyColorOverlayPath = UIBezierPath.bezierPath;
            [shape74CopyColorOverlayPath moveToPoint: CGPointMake(841, 1670)];
            [shape74CopyColorOverlayPath addCurveToPoint: CGPointMake(849, 1678) controlPoint1: CGPointMake(845.42, 1670) controlPoint2: CGPointMake(849, 1673.58)];
            [shape74CopyColorOverlayPath addCurveToPoint: CGPointMake(841, 1686) controlPoint1: CGPointMake(849, 1682.42) controlPoint2: CGPointMake(845.42, 1686)];
            [shape74CopyColorOverlayPath addCurveToPoint: CGPointMake(833, 1678) controlPoint1: CGPointMake(836.58, 1686) controlPoint2: CGPointMake(833, 1682.42)];
            [shape74CopyColorOverlayPath addCurveToPoint: CGPointMake(841, 1670) controlPoint1: CGPointMake(833, 1673.58) controlPoint2: CGPointMake(836.58, 1670)];
            [shape74CopyColorOverlayPath closePath];
            CGContextSaveGState(context);
            CGContextSetShadowWithColor(context, shape74CopyDropShadowOffset, shape74CopyDropShadowBlurRadius, [shape74CopyDropShadow CGColor]);
            [shape74CopyColorOverlay setFill];
            [shape74CopyColorOverlayPath fill];
            CGContextRestoreGState(context);



            CGContextEndTransparencyLayer(context);
            CGContextRestoreGState(context);
        }


        //// Group 72
        {
            CGContextSaveGState(context);
            CGContextSetAlpha(context, 0.5);
            CGContextBeginTransparencyLayer(context, NULL);


            //// Shape 74 copy 2 ColorOverlay Drawing
            UIBezierPath* shape74Copy2ColorOverlayPath = UIBezierPath.bezierPath;
            [shape74Copy2ColorOverlayPath moveToPoint: CGPointMake(821, 1652)];
            [shape74Copy2ColorOverlayPath addCurveToPoint: CGPointMake(829, 1660) controlPoint1: CGPointMake(825.42, 1652) controlPoint2: CGPointMake(829, 1655.58)];
            [shape74Copy2ColorOverlayPath addCurveToPoint: CGPointMake(821, 1668) controlPoint1: CGPointMake(829, 1664.42) controlPoint2: CGPointMake(825.42, 1668)];
            [shape74Copy2ColorOverlayPath addCurveToPoint: CGPointMake(813, 1660) controlPoint1: CGPointMake(816.58, 1668) controlPoint2: CGPointMake(813, 1664.42)];
            [shape74Copy2ColorOverlayPath addCurveToPoint: CGPointMake(821, 1652) controlPoint1: CGPointMake(813, 1655.58) controlPoint2: CGPointMake(816.58, 1652)];
            [shape74Copy2ColorOverlayPath closePath];
            CGContextSaveGState(context);
            CGContextSetShadowWithColor(context, shape74Copy2DropShadowOffset, shape74Copy2DropShadowBlurRadius, [shape74Copy2DropShadow CGColor]);
            [shape74Copy2ColorOverlay setFill];
            [shape74Copy2ColorOverlayPath fill];
            CGContextRestoreGState(context);



            CGContextEndTransparencyLayer(context);
            CGContextRestoreGState(context);
        }


        //// Group 74
        {
            CGContextSaveGState(context);
            CGContextSetAlpha(context, 0.5);
            CGContextBeginTransparencyLayer(context, NULL);


            //// Shape 74 copy 3 ColorOverlay Drawing
            UIBezierPath* shape74Copy3ColorOverlayPath = UIBezierPath.bezierPath;
            [shape74Copy3ColorOverlayPath moveToPoint: CGPointMake(813, 1629)];
            [shape74Copy3ColorOverlayPath addCurveToPoint: CGPointMake(821, 1637) controlPoint1: CGPointMake(817.42, 1629) controlPoint2: CGPointMake(821, 1632.58)];
            [shape74Copy3ColorOverlayPath addCurveToPoint: CGPointMake(813, 1645) controlPoint1: CGPointMake(821, 1641.42) controlPoint2: CGPointMake(817.42, 1645)];
            [shape74Copy3ColorOverlayPath addCurveToPoint: CGPointMake(805, 1637) controlPoint1: CGPointMake(808.58, 1645) controlPoint2: CGPointMake(805, 1641.42)];
            [shape74Copy3ColorOverlayPath addCurveToPoint: CGPointMake(813, 1629) controlPoint1: CGPointMake(805, 1632.58) controlPoint2: CGPointMake(808.58, 1629)];
            [shape74Copy3ColorOverlayPath closePath];
            CGContextSaveGState(context);
            CGContextSetShadowWithColor(context, shape74Copy3DropShadowOffset, shape74Copy3DropShadowBlurRadius, [shape74Copy3DropShadow CGColor]);
            [shape74Copy3ColorOverlay setFill];
            [shape74Copy3ColorOverlayPath fill];
            CGContextRestoreGState(context);



            CGContextEndTransparencyLayer(context);
            CGContextRestoreGState(context);
        }
    }


    //// Cleanup
    CGGradientRelease(twoColor);
    CGColorSpaceRelease(colorSpace);
}

@end
